# Generated by Django 2.2 on 2019-04-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='picture',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='photos_pers_name_c92ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['shot_date'], name='photos_phot_shot_da_19359c_idx'),
        ),
    ]
