# Generated by Django 2.2 on 2019-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190424_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to='shots'),
        ),
        migrations.AddIndex(
            model_name='photoidentification',
            index=models.Index(fields=['person'], name='photos_phot_person__54bda6_idx'),
        ),
        migrations.AddIndex(
            model_name='photoidentification',
            index=models.Index(fields=['photo'], name='photos_phot_photo_i_171ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='photoidentification',
            index=models.Index(fields=['verified'], name='photos_phot_verifie_7704dd_idx'),
        ),
    ]
