# Generated by Django 2.2 on 2019-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190424_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
