# Generated by Django 2.2 on 2019-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190424_1028'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='photoidentification',
            name='photos_phot_verifie_7704dd_idx',
        ),
        migrations.RemoveField(
            model_name='photoidentification',
            name='verified',
        ),
        migrations.AddField(
            model_name='photo',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to='shots/%Y/%m/%d'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['verified'], name='photos_phot_verifie_347508_idx'),
        ),
    ]
